/**
 * @fileoverview Constellation — 2D scatter of all 136 entry centroids in
 * the embedding space. Renders public/rag/constellation.json as an SVG
 * scatter with hover labels.
 *
 * This is the conference's "philosophy of embedding" money shot: the
 * audience literally sees the corpus laid out by thematic proximity.
 * Two interviewees who never met but whose words land within 0.12
 * cosine of each other on this topic appear as nearby dots on the
 * scatter.
 *
 * Static — no live retrieval. The data file is precomputed by
 * rag/precompute.mjs against the populated Pinecone index.
 */

import { useEffect, useState, useRef, useMemo } from 'react';
import { loadConstellation } from '../../services/ragClient';

/**
 * Constellation — SVG scatter of corpus entries in 2D embedding space.
 *
 * @component
 * @param {Object} props
 * @param {number} [props.width=720]
 * @param {number} [props.height=720]
 * @param {(point: ConstellationPoint) => void} [props.onSelect] - Click handler.
 * @param {string} [props.className]
 * @returns {React.ReactElement}
 */
export default function Constellation({
  width = 720,
  height = 720,
  onSelect = null,
  className = '',
}) {
  const [data, setData] = useState(null);
  const [error, setError] = useState(null);
  const [hover, setHover] = useState(null);
  const svgRef = useRef(null);

  useEffect(() => {
    let cancelled = false;
    loadConstellation()
      .then((json) => { if (!cancelled) setData(json); })
      .catch((e) => { if (!cancelled) setError(e?.message || 'Failed to load.'); });
    return () => { cancelled = true; };
  }, []);

  // Padding: keep labels from spilling off the edges.
  const PAD = 40;
  const innerW = width - 2 * PAD;
  const innerH = height - 2 * PAD;
  const projected = useMemo(() => {
    if (!data?.points) return [];
    return data.points.map((p) => ({
      ...p,
      cx: PAD + ((p.x + 1) / 2) * innerW,
      cy: PAD + ((1 - p.y) / 2) * innerH, // flip y so positive is up
      r: 3 + Math.log10((p.chunk_count || 1) + 1),
    }));
  }, [data, innerW, innerH]);

  if (error) {
    return (
      <div className={`rag-constellation-error ${className} text-sm text-stone-500 p-4`}>
        Embedding-space map not yet available. It is generated by
        rag/precompute.mjs against the populated Pinecone index.
      </div>
    );
  }

  if (!data) {
    return (
      <div
        className={`rag-constellation-loading ${className} bg-stone-50 rounded`}
        style={{ width, height }}
        aria-hidden="true"
      />
    );
  }

  return (
    <figure className={`rag-constellation ${className}`}>
      <svg
        ref={svgRef}
        width={width}
        height={height}
        viewBox={`0 0 ${width} ${height}`}
        role="img"
        aria-label="Two-dimensional projection of the corpus into embedding space; dots represent interviews positioned by thematic similarity."
        className="bg-stone-50 rounded-lg border border-stone-200"
      >
        {/* Subtle reference grid */}
        <g aria-hidden="true">
          {[0.25, 0.5, 0.75].map((f) => (
            <line
              key={`h-${f}`}
              x1={PAD}
              y1={PAD + f * innerH}
              x2={PAD + innerW}
              y2={PAD + f * innerH}
              stroke="#e5e5e5"
              strokeWidth={1}
              strokeDasharray="2 4"
            />
          ))}
          {[0.25, 0.5, 0.75].map((f) => (
            <line
              key={`v-${f}`}
              x1={PAD + f * innerW}
              y1={PAD}
              x2={PAD + f * innerW}
              y2={PAD + innerH}
              stroke="#e5e5e5"
              strokeWidth={1}
              strokeDasharray="2 4"
            />
          ))}
        </g>

        {/* Points */}
        <g>
          {projected.map((p) => (
            <circle
              key={p.entry_number}
              cx={p.cx}
              cy={p.cy}
              r={p.r}
              className="fill-red-700/70 hover:fill-red-700 cursor-pointer transition-colors"
              onMouseEnter={() => setHover(p)}
              onMouseLeave={() => setHover(null)}
              onClick={() => onSelect?.(p)}
              tabIndex={0}
              role="button"
              aria-label={`${p.entry_subject}, entry ${p.entry_number}`}
            />
          ))}
        </g>

        {/* Hover label */}
        {hover && (
          <g aria-hidden="true">
            <rect
              x={Math.min(hover.cx + 8, width - 200)}
              y={Math.max(hover.cy - 28, 4)}
              width={190}
              height={36}
              rx={4}
              fill="#1c1917"
              opacity={0.92}
            />
            <text
              x={Math.min(hover.cx + 16, width - 192)}
              y={Math.max(hover.cy - 12, 18)}
              fill="#fafaf9"
              fontSize={12}
              fontFamily="ui-sans-serif, system-ui, sans-serif"
            >
              {hover.entry_subject}
            </text>
            <text
              x={Math.min(hover.cx + 16, width - 192)}
              y={Math.max(hover.cy + 2, 32)}
              fill="#a8a29e"
              fontSize={10}
              fontFamily="ui-sans-serif, system-ui, sans-serif"
            >
              Entry #{hover.entry_number} · {hover.chunk_count} chunks
            </text>
          </g>
        )}
      </svg>
      <figcaption className="text-xs text-stone-500 mt-2 max-w-xl">
        Each dot is one of {projected.length} oral history interviews, positioned by 2D PCA
        projection of its embedding-space centroid. Dots that sit close to each other share
        thematic territory even when the speakers never met. Hover for the interviewee&apos;s
        name; click to open the interview page.
      </figcaption>
    </figure>
  );
}
